language: ruby
rvm:
- 2.6.3
services:
- postgresql
before_script:
- psql -c 'create database blog_test;' -U postgres
env:
  global:
    secure: B+J2To8sTW0psiEfp3nWgL0hKFC3+MvYZi9rkXDWDL5EvaAMbisWSnvfed6voyDQTO77FoulSZEYYbOuJgaOVR48L+ZVpzHmrXY1aXyFusA/xW0avCOUkl4LmwbjMoCHDU5K6RCNu7onET+ZLiorGLJXfEXrPZi65gHZ9WMHiJ/R/cG4TbVoS8xquv8gdAsX8KFnLP7KznXEyMQ1mOPf4+XQbK6zMEX17WJe95C6gsJZDSNv//+MgHnw37sy0DqYWURma1wx+/8tY8BxCTiZmiAvpTykYIm7mT8ChptqVpiwr2oLRBtDMCHY30O+wWYF7muBdUBpD/skQaBmxve0JuUnrdvhLPNrkC8ZrFpS5mS6ZOcr++2raR1d/3mT9nCJmgdpQWzo/BGqrD3k07DPO5bDshhW6p1Kt69OsvebASZ938D6DThHEfOVjL10kIzwBY1ObhANgEsBL6Kse/ZGbebU8MSC1EMuXO8WvtA4K8mTQYbvzccO6FskBgEbwaaSYEks5WQK8sbdEBnNKhU8S0aakI7IKUKlfar0FgoVfZ7s4TZV3bjVbdcWlUGgOdlXAjcj9LT0hrqHFBhay3p3NQ+xTVhFDgeqLrFfJs4hDbLf2gD/g2P6IDnLNj25y68wGm18WcboazibDI0Y7bV1mGapV03WYymhgxT1gqewLDU=
