development:
  SORCERY_GITHUB_KEY: "cd5cce5cecb001da9a3c"
  SORCERY_GITHUB_SECRET: "7ab53a32ea1e9b72bd4f5d1387b8c6cedf874ed2"
  SORCERY_GITHUB_CALLBACK_URL: "http://localhost:3000/oauth/callback?provider=github"
  S3_BUCKET_NAME: "rails-flashcards"
  AWS_ACCESS_KEY_ID: "AKIAJRR45WSUYG6YUQHA"
  AWS_SECRET_ACCESS_KEY: "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"
  AWS_REGION: "us-east-2"
  
test: 
  SORCERY_GITHUB_KEY: "cd5cce5cecb001da9a3c"
  SORCERY_GITHUB_SECRET: "7ab53a32ea1e9b72bd4f5d1387b8c6cedf874ed2"
  SORCERY_GITHUB_CALLBACK_URL: "http://localhost:3000/oauth/callback?provider=github"